{% set version = "9.1.1" %}

{% set base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: ijar
  version: {{ version }}

source:
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: a6f66e26c8f4ca04fa83c796a404eff0544bd78336fbbcd122c9e10cbec4a5d7

  - fn: bazel
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64  # [build_platform == "linux-64"]
    sha256: c5dc3d1fa6b9a834c1b89adfd3791fe90d9e39ccf79baac7f1daf3bba3c1147d  # [build_platform == "linux-64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-x86_64  # [build_platform == "osx-64"]
    sha256: 55f26ecd2799d4de7ddd35e3828ff31e1f3a63532bf877a561e81fe11bec3f26  # [build_platform == "osx-64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64  # [build_platform == "osx-arm64"]
    sha256: c079130049a63710f67dcb4133cf6d9384fa12e46b4efce6ce8183a83f6c4342  # [build_platform == "osx-arm64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain >=0.5.0
    - openjdk
    - sed

test:
  commands:
    - test -f $PREFIX/bin/ijar
    - test -f $PREFIX/bin/zipper

about:
  home: https://github.com/bazelbuild/bazel/tree/master/third_party/ijar
  license: Apache-2.0
  license_family: MIT
  license_file: third_party/ijar/LICENSE
  summary: A tool for generating interface .jars from normal .jars

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/bazel
