{% set version = "5.4.1" %}

{% set base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: ijar
  version: {{ version }}

source:
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: dcff6935756aa7aca4fc569bb2bd26e1537f0b1f6d1bda5f2b200fa835cc507f
  - url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-x86_64  # [build_platform == "osx-64"]
    sha256: ad97d9c825afc797532f6c43577afc76b6eb14673496cdcd1ee23930ee5a743e   # [build_platform == "osx-64"]
    fn: bazel                                                                  # [build_platform == "osx-64"]
  - url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64   # [build_platform == "osx-arm64"]
    sha256: 4f73904e99881c9016546dbf749d3a3271f959143e853b5d64742acd25b85a10   # [build_platform == "osx-arm64"]
    fn: bazel                                                                  # [build_platform == "osx-arm64"]
  - url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64   # [build_platform == "linux-64"]
    sha256: 1bad567536ec4bc2a3c857d590ae43353a96e43df1454dabe13a70d59bf5ffdc   # [build_platform == "linux-64"]
    fn: bazel                                                                  # [build_platform == "linux-64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain
    - openjdk

test:
  commands:
    - test -f $PREFIX/bin/ijar
    - test -f $PREFIX/bin/zipper

about:
  home: https://github.com/bazelbuild/bazel/tree/master/third_party/ijar
  license: Apache-2.0
  license_family: MIT
  license_file: third_party/ijar/LICENSE
  summary: A tool for generating interface .jars from normal .jars

extra:
  recipe-maintainers:
    - xhochy
    - h-vetinari
