{% set name = "ijar" %}
{% set version = "6.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: 4cf4d264bff388ee0012735728630d23832d3c9d021383b2fadceadb0775dd6b
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-darwin-x86_64  # [build_platform == "osx-64"]
    sha256: ef6f0be3fa6e44e475b98828774ae6e52c956a1b96be48f9cd2f1567c4f53e56  # [build_platform == "osx-64"]
    fn: bazel  # [build_platform == "osx-64"]
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64  # [build_platform == "osx-arm64"]
    sha256: e3639d541515e370eaba215f80ebe1f96a4f10c92fa77bc9f15b7b6c5b24f66d  # [build_platform == "osx-arm64"]
    fn: bazel  # [build_platform == "osx-arm64"]
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64  # [build_platform == "linux-64"]
    sha256: c83e3e49d4be7f15f594bb1f5b7531381ad7d1fcb53fb9f97d611664efe0d84e  # [build_platform == "linux-64"]
    fn: bazel  # [build_platform == "linux-64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain
    - openjdk

test:
  commands:
    - test -f $PREFIX/bin/ijar
    - test -f $PREFIX/bin/zipper

about:
  home: https://github.com/bazelbuild/bazel/tree/master/third_party/ijar
  license: Apache-2.0
  license_family: MIT
  license_file: third_party/ijar/LICENSE
  summary: A tool for generating interface .jars from normal .jars

extra:
  recipe-maintainers:
    - xhochy
