{% set name = "ijar" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: 820a94dbb14071ed6d8c266cf0c080ecb265a5eea65307579489c4662c2d582a
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-darwin-x86_64  # [build_platform == "osx-64"]
    sha256: dbf2f955fe5ebe79aded90a0b400a71853feaf0772fb2fc95f5c5f2ba6804b98  # [build_platform == "osx-64"]
    fn: bazel  # [build_platform == "osx-64"]
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64  # [build_platform == "osx-arm64"]
    sha256: 8ab6cf61e8fa5c8dadb3873315c2865ce5e2b5bcf6a165dc7368554dbaf0a520  # [build_platform == "osx-arm64"]
    fn: bazel  # [build_platform == "osx-arm64"]
  - url: https://github.com/bazelbuild/bazel/releases/download/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64  # [build_platform == "linux-64"]
    sha256: 8726379b76dc69bb652f0dea8658f2e0304a98dbbaf8a773c6726a3052ef80d5  # [build_platform == "linux-64"]
    fn: bazel  # [build_platform == "linux-64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain
    - openjdk

test:
  commands:
    - test -f $PREFIX/bin/ijar
    - test -f $PREFIX/bin/zipper

about:
  home: https://github.com/bazelbuild/bazel/tree/master/third_party/ijar
  license: Apache-2.0
  license_family: MIT
  license_file: third_party/ijar/LICENSE
  summary: A tool for generating interface .jars from normal .jars

extra:
  recipe-maintainers:
    - xhochy
