{% set version = "9.0.0" %}

{% set base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: ijar
  version: {{ version }}

source:
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: dfa496089624d726a158afcac353725166f81c5708ee1ecc9e662f2891b3544d

  - fn: bazel
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64   # [build_platform == "linux-64"]
    sha256: ecc5a225b5fcad3e0c08ec24d266f2b2a75b24259180e64583bb2d3c1586e986   # [build_platform == "linux-64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-x86_64  # [build_platform == "osx-64"]
    sha256: 1166bfa2139e4475679dd20bdeac252809b7ad1cd7f381e4d9c6f108858ac4ca   # [build_platform == "osx-64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64   # [build_platform == "osx-arm64"]
    sha256: 97b647cadcb90514f4b4bd2cbbceed37d57bcda48d429edc62abcd72c03e5b40   # [build_platform == "osx-arm64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain >=0.5.0
    - openjdk
    - sed

test:
  commands:
    - test -f $PREFIX/bin/ijar
    - test -f $PREFIX/bin/zipper

about:
  home: https://github.com/bazelbuild/bazel/tree/master/third_party/ijar
  license: Apache-2.0
  license_family: MIT
  license_file: third_party/ijar/LICENSE
  summary: A tool for generating interface .jars from normal .jars

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/bazel
